#!/usr/bin/env bash

readonly REVIEWER_EXIT_SUCCESS=0
readonly REVIEWER_EXIT_EVIDENCE_INTEGRITY=10
readonly REVIEWER_EXIT_COMPATIBILITY=20
readonly REVIEWER_EXIT_REPRODUCTION=30
readonly REVIEWER_EXIT_INFRASTRUCTURE=40
